#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""LTspice-backend integration tests.

These exercise the optional ``use_ltspice`` path (LTspice's own
``-netlist``). They are skipped automatically when LTspice.exe is not
installed, so CI on Linux stays green while a developer machine with
LTspice gets real coverage.
"""
from __future__ import annotations

import sys

import pytest

from ltspice_converter import (
    asc_to_netlist, netlist_to_asc, topology_equivalent,
)
from ltspice_converter._shared import decode_asc_bytes
from ltspice_converter.parser.asc_parser import _find_ltspice_exe

ltspice = pytest.mark.skipif(
    _find_ltspice_exe() is None, reason="LTspice.exe not installed"
)

RC_NETLIST = ("V1 in 0 AC 1\nR1 in out 1k\nC1 out 0 1u\n"
              ".ac dec 20 1 100k\n.end")
# A well-formed .asc straight from the converter (cleanly wired, so
# LTspice's strict netlister and the pure-Python extractor agree).
RC_ASC = netlist_to_asc(RC_NETLIST)


@ltspice
def test_ltspice_backend_runs_headless():
    """use_ltspice=True returns LTspice's canonical netlist (proves the
    first-run dialog is dismissed and -netlist runs headlessly)."""
    net = asc_to_netlist(RC_ASC, use_ltspice=True)
    assert "Generated by LTspice" in net
    low = net.lower()
    assert "\nr1 " in low or low.startswith("r1 ")
    assert "\nc1 " in low


@ltspice
def test_ltspice_and_pure_python_agree_on_simple_rc():
    """For a plain R/C/V circuit (no vendor symbols) the two backends
    must produce the same topology, and both must match the source."""
    net_lt = asc_to_netlist(RC_ASC, use_ltspice=True)
    net_py = asc_to_netlist(RC_ASC, use_ltspice=False)
    assert topology_equivalent(net_lt, net_py)[0]
    assert topology_equivalent(net_lt, RC_NETLIST)[0]


def test_pure_python_backend_is_deterministic():
    """use_ltspice=False never shells out, regardless of LTspice install."""
    a = asc_to_netlist(RC_ASC, use_ltspice=False)
    b = asc_to_netlist(RC_ASC, use_ltspice=False)
    assert a == b


# Two resistors at the exact same position -> LTspice pops a blocking
# "Duplicate overlapping components found ..Delete?" message box.
_OVERLAP_ASC = """Version 4
SHEET 1 880 680
SYMBOL res 100 100 R0
SYMATTR InstName R1
SYMATTR Value 1k
SYMBOL res 100 100 R0
SYMATTR InstName R2
SYMATTR Value 2k
SYMBOL voltage 0 100 R0
SYMATTR InstName V1
SYMATTR Value 1
FLAG 16 196 0
FLAG 16 100 a
TEXT 0 300 Left 2 !.op
"""


@ltspice
@pytest.mark.skipif(sys.platform != "win32", reason="watchdog is Windows-only")
def test_overlapping_components_dialog_is_auto_dismissed():
    """The 'duplicate overlapping components' modal must be dismissed
    automatically: the call completes quickly (not after the timeout)
    and keeps BOTH components (No = don't delete)."""
    import time
    t0 = time.time()
    net = asc_to_netlist(_OVERLAP_ASC, use_ltspice=True)
    elapsed = time.time() - t0
    assert elapsed < 15, f"call blocked on the dialog ({elapsed:.0f}s)"
    low = net.lower()
    assert "\nr1 " in low and "\nr2 " in low, "a component was deleted"


@ltspice
@pytest.mark.skipif(sys.platform != "win32", reason="Windows-only")
def test_no_orphaned_ltspice_after_overlap_run():
    """After dismissing the dialog, no LTspice process is left behind."""
    import subprocess
    asc_to_netlist(_OVERLAP_ASC, use_ltspice=True)
    out = subprocess.run(
        ["tasklist", "/FI", "IMAGENAME eq LTspice.exe", "/NH"],
        capture_output=True, text=True,
    ).stdout
    assert "LTspice.exe" not in out, "an LTspice process was left orphaned"


def test_decode_bomless_utf16():
    """BOM-less UTF-16 LE (e.g. LTspice's UniversalOpAmp*.asc) decodes
    to real text, not a NUL-riddled string."""
    raw = "Version 4\nSHEET 1 100 100\n".encode("utf-16-le")  # no BOM
    text = decode_asc_bytes(raw)
    assert text.startswith("Version 4")
    assert "\x00" not in text
    assert "SHEET" in text


def test_decode_utf16_with_bom_and_utf8():
    assert decode_asc_bytes("Version 4\n".encode("utf-16-le")
                            ).startswith("Version 4")
    assert decode_asc_bytes(b"\xff\xfe" + "Vé\n".encode("utf-16-le")
                            ).startswith("Vé")
    assert decode_asc_bytes("R1 a b 1k\n".encode("utf-8")
                            ).startswith("R1 a b 1k")
    # bare 0xB5 (cp1252 µ) must not raise
    assert "\xb5" in decode_asc_bytes(b"C1 a 0 10\xb5\n")
